### ISSUE TITLE
[BUG]: <Wrong display of height and width values ​​in DeepFace.represent function>

### ISSUE THREAD

**Issue by MinhKint** [serengil/deepface#1216] opened 2024-04-26 09:02 UTC
### Before You Report a Bug, Please Confirm You Have Done The Following...

- [X] I have updated to the latest version of the packages.
- [X] I have searched for both [existing issues](https://github.com/serengil/deepface/issues) and [closed issues](https://github.com/serengil/deepface/issues?q=is%3Aissue+is%3Aclosed) and found none that matched my issue.

### DeepFace's version

0.0.90

### Python version

3.11.3

### Operating System

Windows11

### Dependencies

tensorflow==2.14.0
keras==2.14.0

### Reproducible example

```Python
I run this in google colab and detect: 

DeepFace.represent(img_path = r"/content/img.webp", detector_backend = 'skip')
```

### Relevant Log Output

The program still OK

### Expected Result

Output:
[{'embedding': [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.006433258973663661,
   0.0,
   0.0,
   0.0,
   ...],
  'facial_area': {'x': 0, 'y': 0, 'w': 700, 'h': 3},
  'face_confidence': 0}]
  
  Meanwhile, the image I used has a shape of 700,700,3

### What happened instead?

Wrong index of img

### Additional Info

Line 87, def represent() in representation.py in modules

The line original: "facial_area": {"x": 0, "y": 0, "w": img.shape[1], "h": img.shape[2]} 

I think it should be: "facial_area": {"x": 0, "y": 0, "w": img.shape[0], "h": img.shape[1]}

**Comment by serengil** [comment] 2024-04-26 09:06
@MinhKint good spot! thank you for the information.

Seems you already find the root cause of the issue. Do you mind to create a PR for this? Want to see this is resolved by you in the commit history. If you do not want, I can fix this of course.

**Closed** 2024-05-01 10:05 UTC
Labels: bug

**Comment by MinhKint** [comment] 2024-05-02 01:41
Thank you for sending, because I had an unexpected job the past few days so
I couldn't check the email you sent.
