### ISSUE TITLE
[BUG]: represent accidentally converting back to rgb

### ISSUE THREAD

**Issue by logasja** [serengil/deepface#1262] opened 2024-06-22 16:10 UTC
### Before You Report a Bug, Please Confirm You Have Done The Following...

- [X] I have updated to the latest version of the packages.
- [X] I have searched for both [existing issues](https://github.com/serengil/deepface/issues) and [closed issues](https://github.com/serengil/deepface/issues?q=is%3Aissue+is%3Aclosed) and found none that matched my issue.

### DeepFace's version

0.0.90

### Python version

DeepFace Docker Environment

### Operating System

DeepFace Docker Environment

### Dependencies

Using DeepFace Docker Environment

### Reproducible example

```Python
In representation.py starting at line 98:

If skipping detection and loading an image directly, line 82:

img, _ = image_utils.load_image(img_path)

will return a bgr image which is then reversed to rgb at line 103:
```python
img = img[:, :, ::-1]
```
```


### Relevant Log Output

_No response_

### Expected Result

_No response_

### What happened instead?

_No response_

### Additional Info

_No response_

**Comment by serengil** [comment] 2024-06-22 16:37
It is independent you skip or not detection. Images are fed as rgb to cnn models. Its corresponding comment has typo but it is not a bug.

**Comment by logasja** [comment] 2024-06-22 16:45
So then the expected input to the trained models is RGB and not BGR?

**Comment by serengil** [comment] 2024-06-23 11:49
Closing this because it is not an issue. But feel free to continue to discuss in this thread if you have any questions or concerns.

**Closed by serengil** 2024-06-23 11:49 UTC
Labels: bug

**Comment by logasja** [comment] 2024-06-23 23:40
Thank you for the clarification, I have been using the models directly and thought they were trained in BGR.
