### ISSUE TITLE
AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'

### ISSUE THREAD

**Issue by Hwang64** [serengil/deepface#246] opened 2021-05-27 08:47 UTC
When using the deepface, I use conda the create a virsual envrionment, and using pip install deepface to install the packdge, but when I run the code, I met the error:
AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'
deepface==0.5.1
tensorflow==2.5.0
keras==2.4.3
![image](https://user-images.githubusercontent.com/37236874/119795531-24549300-bf0b-11eb-8ff6-9974bb580cb1.png)

**Comment by serengil** [comment] 2021-05-27 08:53
Could you run it on tensorflow 2.2.0?

I think it is 2.5 version related problem.

**Comment by Hwang64** [comment] 2021-05-27 09:31
When I pip install tensorflow==2.2.0, I meet a new error
AttributeError: module 'tensorflow.compat.v2' has no attribute '__internal__'
![image](https://user-images.githubusercontent.com/37236874/119802584-3e916f80-bf11-11eb-9617-418fd6eb1d96.png)

**Comment by duongminhhieu16** [comment] 2021-05-27 10:21
I met the first error and I found out the error is from keras 2.4.3 is somehow not compatible with tensorflow 2.5.0. The error comes from where you import directly keras. Changing all import "keras..." to "tensorflow.keras..." will fix this.

**Comment by Hwang64** [comment] 2021-05-27 10:52
> I met the first error and I found out the error is from keras 2.4.3 is somehow not compatible with tensorflow 2.5.0. The error comes from where you import directly keras. Changing all import "keras..." to "tensorflow.keras..." will fix this.

Thank you for your suggestion, but changing import keras to import tensorflow.keras is labourious job, do you have some effective ways to do it?

**Comment by serengil** [comment] 2021-05-27 12:58
Could you share the whole exception message? Dumping log is not coming from any deepface related module.

**Comment by Hwang64** [comment] 2021-05-27 13:40
the whole exception message is:
![image](https://user-images.githubusercontent.com/37236874/119836247-2aab3500-bf34-11eb-8d7a-8711eafef3bf.png)

**Comment by serengil** [comment] 2021-05-27 13:45
Oke, I found a workaround. But it is going to be resolved in the next release. I will publish it in the next couple of days.

**Comment by Hwang64** [comment] 2021-05-27 14:44
> Oke, I found a workaround. But it is going to be resolved in the next release. I will publish it in the next couple of days.

Thank you for your reply, is there a temporary solution to make the deepface run based on the current veriosn (deepface==0.5.1& &tensorflow==2.5.0&keras==2.4.3)?

**Comment by serengil** [comment] 2021-05-27 14:47
Try to run the following commands respectively

pip uninstall deepface
pip uninstall tensorflow
pip uninstall keras

pip install tensorflow==2.2.0
pip install keras==2.4.3
pip install mtcnn==0.1.0
pip install deepface==0.0.51 --no-deps

**Comment by serengil** [comment] 2021-05-27 18:34
the problem is that its dependency mtcnn causes that trouble.

currently, i am using python 3.8.5, tensorflow 2.2.0, keras 2.4.3, mtcnn 0.1.0 and it works

you might downgrade to tensorflow 1.9.X to fix this issue.

**Comment by serengil** [comment] 2021-05-27 18:35
I will publish the next release soon (half hour later) when I run unit tests successfully. You might want to wait.

**Comment by serengil** [comment] 2021-05-27 19:41
This is handled in 0.0.52. It will be published soon.

**Closed by serengil** 2021-05-27 19:41 UTC
Labels: dependencies

**Comment by serengil** [comment] 2021-05-27 19:46
0.0.52 is just published. please update deepface library. and use a different detector_backend than mtcnn

DeepFace.verify("img1.jpg", "img2.jpg", detector_backend = 'opencv')

**Comment by ImMainak** [comment] 2021-06-03 11:01
Sir I'm still facing the same issue in 0.0.53

**Comment by serengil** [comment] 2021-06-03 11:03
@ImMainak please share the code you are running and the whole exception message you got.

**Comment by ImMainak** [comment] 2021-06-03 11:13
From the mentioned solution I downgraded Tensorflow to 2.2.0 and installed
deepface version 0.0.52 but here it's showing that two picture of different
people are of a same person. Here I'm sharing my code and the output I'm
getting

Code :-

from deepface import DeepFace
import pandas as pd
df = DeepFace.verify("E:\Python_Test_Data\Test2.jpg",
"E:\Python_Test_Data\Test1.jpg", detector_backend='opencv')
print(df)

Output :-

vgg_face_weights.h5 will be downloaded...
Access denied with the following error:
Unable to open file (unable to open file: name =
'C:\Users\Mainak/.deepface/weights/vgg_face_weights.h5', errno = 2, error
message = 'No such file or directory', flags = 0, o_flags = 0)
Pre-trained weight could not be loaded.
You might try to download the pre-trained weights from the url
https://drive.google.com/uc?id=1CPSeum3HpopfomUEK1gybeuIVoeJT_Eo  and copy
it to the  C:\Users\Mainak/.deepface/weights/vgg_face_weights.h5

  Too many users have viewed or downloaded this file recently. Please
try accessing the file again later. If the file you are trying to
access is particularly large or is shared with many people, it may
take up to 24 hours to be able to view or download the file. If you
still can't access a file after 24 hours, contact your domain
administrator.

You may still be able to access the file from the browser:

https://drive.google.com/uc?id=1CPSeum3HpopfomUEK1gybeuIVoeJT_Eo

WARNING: AutoGraph could not transform <function
Model.make_predict_function.<locals>.predict_function at
0x000001F2E00AD8B0> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the
verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the
full output.
Cause:
To silence this warning, decorate the function with
@tf.autograph.experimental.do_not_convert
{'verified': True, 'distance': 0.0504792375197427,
'max_threshold_to_verify': 0.4, 'model': 'VGG-Face', 'similarity_metric':
'cosine'}

**Comment by serengil** [comment] 2021-06-03 11:15
your trouble is totally different to this issue.

1- use the latest version: 0.0.53

2- download the weight manually from the browser and copy it to the HOME/.deepface/weights folder - follow the instructions in the troubleshooting and faq in the read me of the repo.

**Comment by ImMainak** [comment] 2021-06-03 11:20
Thank you for this suggestion.
