### ISSUE TITLE
cosine distance calculation in mongodb aggregate

### ISSUE THREAD

**Issue by sanatani9** [serengil/deepface#589] opened 2022-11-02 16:39 UTC
Hello 
by following your code we can find distance using Euclidean 
here is example of aggregation I am using.

`query = deepface_collection.aggregate( [
	{
	    "$addFields": { 
	        "target_embedding": target_embedding
	    }
	}
	, 
{"$unwind" : { "path" : "$embedding", "includeArrayIndex": "embedding_index"}}
	, {"$unwind" : { "path" : "$target_embedding", "includeArrayIndex": "target_index" }}
	, {
	    "$project": {
	        "img_path": 1,
	        "embedding": 1,
	        "name" : 1,
	        "target_embedding": 1,
	        "compare": {
	            "$cmp": ['$embedding_index', '$target_index']
	        }
	    }
	}
	, {"$match": {"compare": 0}}
	, {
	  "$group": {
	    "_id": "$img_path",
	    "name" : { "$first": "$name" },
	    "distance": {
	        "$sum": {
	            "$pow": [{
	                "$subtract": ['$embedding', '$target_embedding']
	            }, 2]
	        }
	    }
	  }
	}
	, { 
	    "$project": {
	    	"name" : 1,
	        "_id": 1
	        #, "distance": 1
	        , "distance": {"$sqrt": "$distance"}
	    }
	}, { 
	    "$project": {
	    	"name" : 1,
	        "_id": 1
	        , "distance": 1
	        , "cond": { "$lte": [ "$distance", 4.15 ] }
	    }
	}
	, {"$match": {"cond": True}}
	, { "$sort" : { "distance" : 1 } }
	] )`

Now can you please help me and let me know what changes I need to make to use consine?

**Comment by serengil** [comment] 2022-11-03 09:37
this is mongo related question. you can ask this on stackoverflow to get faster answers. i am closing this because this is not a bug.

**Closed by serengil** 2022-11-03 09:37 UTC
Labels: question
