### ISSUE TITLE
Wrong face alignment if the rotation angle is too big.

### ISSUE THREAD

**Issue by Nikita7x** [serengil/deepface#468] opened 2022-05-04 14:08 UTC
For method` FaceDetector.detect_faces()` and functions like `functions.preprocess_face()` face alignment messes up if in input image face rotation angle is too big.
![Artboard 2](https://user-images.githubusercontent.com/77989743/166698751-5c6c9bf3-301b-41e9-be10-a573e65fffb9.png)

Looks like if angle is somewhat bigger than 45 degrees, then face will be aligned, but rotated 90 degrees.

**Comment by serengil** [comment] 2022-05-04 18:51
if your detector backend is opencv - which is default - it might detect many eyes. that is the reason why you cannot align it properly.

i recommend you to use retinaface detector. it comes with high performance for detection but it is very slow.

to sum up, this is not a bug. it is a known issue. you should either select the robustness or speed.

**Comment by Nikita7x** [comment] 2022-05-05 06:17
Sure, @serengil. But I'm using retina face detector for that. I also tried other detectors and they work pretty much the same way

**Comment by serengil** [comment] 2022-05-07 19:30
okay. that is a problem. i will research it.

**Comment by serengil** [comment] 2022-05-22 01:01
this is fixed in the retina-face: https://github.com/serengil/retinaface/commit/cfd2be2c5b37fdf9314deeb4bb6c141c1e32aace

**Closed by serengil** 2022-05-22 01:01 UTC
Labels: dependencies
