### ISSUE TITLE
Keras models have a memory leak when used in a loop

### ISSUE THREAD

**Issue by ethanrwilson1998** [serengil/deepface#697] opened 2023-03-13 03:13 UTC
I was having a creeping memory issue calling DeepFace.represent(...) in my training loop with Facenet512.  System memory was increasing by just a few MB per batch, but after a few hundred iterations my model's training would slow exponentially.  I narrowed it down to the model.predict call and found that it was using a Keras backend.  Replacing the model.predict(img) call with model(img) stopped the leak but was slow.  I am on tensorflow 2.11.0 and Keras 2.11.0, which I believe are currently the default versions when installing this package with pip.

I found this post (https://github.com/keras-team/keras/issues/13118) and followed some of the solutions.  I placed the following code at the top of my train code: 
```
import keras.backend as K
cfg = K.tf.compat.v1.ConfigProto()
cfg.gpu_options.allow_growth = True
K.set_session(K.tf.compat.v1.Session(config=cfg))
```
and periodically (every 1024 iterations) will call
```
K.clear_session()
```
This fixed my problem.

@serengil I don't know if it would make sense to put the solution I came up with into the package because calling keras.backend could affect peoples' code if they are using their own Keras models.  But when looking at old issues to try to find the problem I was facing, I saw that a few people have brought up issues running deepface in a loop before.  I think that this is the cause.

**Comment by serengil** [comment] 2023-03-13 08:29
Good workaround. But IMO this should be called in client side not in the library. Closing this issue. Hope this helps people having same problem.

**Comment by serengil** [comment] 2023-03-13 09:58
or i can check how many times represent function called in the current session, and apply this if it is greater than a threshold value.

**Comment by LoganRebecca** [comment] 2023-03-17 12:27
same here, I try to test with really simple code:
import torch
from tqdm import tqdm
from deepface import DeepFace
# Model
img = '6.jpg'  # or file, PIL, OpenCV, numpy, multiple
import tensorflow.keras.backend as K
# Inference
for i in tqdm(range(1000)):
        K.clear_session()
        objs = DeepFace.analyze(img_path = img,
                actions = ['age', 'gender', 'race'],detector_backend ='dlib'
                )
        print(objs)
        import gc
        gc.collect()

And the memory leak is there until OOM. can you help me solve this issue?

**Comment by qcbegin** [comment] 2023-03-18 12:44
I encountered the same memory problem when iteratively calling `analyze()`. I checked the post mentioned by @ethanrwilson1998 and they mentioned that substituting the `predict()` with `predict_on_batch()` would perfectly solve this issue:

> **If you have GPU**: just use `predict_on_batch()` and batch your predictions (a.k.a. put all the images you need the prediction for in one set). **_NO LOOP NEEDED_**
> 
> **On other systems**: Using `predict_on_batch()` could be dangerous in terms of memory available, therefore do the same procedure as above with `predict` while specifying the `batch_size`
> 
> N.B.: `predict()` is not intended to be used in a loop, the only exception to this rule could be that the image you will predict is dependent from earlier results.

I guess this solution could be applied to the relevant functions of this library to resolve the memory leak issue happened in loops.

**Comment by LoganRebecca** [comment] 2023-03-20 06:18
I also had a memory leak when I called this `analyze()` interface in batch using flask Api, this may not be batch processing multiple images, but batch processing one image at a time, I think the memory overflow problem of the loop still needs to locate the cause

**Comment by SH2282000** [comment] 2023-03-20 12:55
Hi, 

I do not know this repository but agree on @qcbegin answer. For example, from [line 672](https://github.com/serengil/deepface/blob/6fb20deb1ff4feea698f3d764ab19f9a03071e6e/deepface/DeepFace.py#L672), the `for` loop should be replaced by a `map` call and the results should be stored within an array before executing the inferences.

In this case:

```python
    for img, region, confidence in img_objs:
        # custom normalization
        img = functions.normalize_input(img=img, normalization=normalization)

        # represent
        if "keras" in str(type(model)):
            # new tf versions show progress bar and it is annoying
            embedding = model.predict(img, verbose=0)[0].tolist()
```

could be replaced _roughly_ by: 
```python
nomalization = lambda image: (functions.normalize_input(img=image, normalization=normalization))
images = map(nomalization, img_objs[:,0])
if "keras" in str(type(model)):
    embeddings = model.predict_on_batch(images)

```

**Comment by serengil** [comment] 2023-10-18 12:29
Would you please test [this PR](https://github.com/serengil/deepface/pull/857) for your large scale datasets?

**Comment by serengil** [comment] 2023-10-22 18:44
closed after PR - https://github.com/serengil/deepface/pull/857

**Closed by serengil** 2023-10-22 18:44 UTC
Labels: enhancement
