### ISSUE TITLE
[BUG]: DeepFace unable to recognize a face with slightly non-straight angle

### ISSUE THREAD

**Issue by alex-rsk** [serengil/deepface#1274] opened 2024-07-11 10:08 UTC
### Before You Report a Bug, Please Confirm You Have Done The Following...

- [X] I have updated to the latest version of the packages.
- [X] I have searched for both [existing issues](https://github.com/serengil/deepface/issues) and [closed issues](https://github.com/serengil/deepface/issues?q=is%3Aissue+is%3Aclosed) and found none that matched my issue.

### DeepFace's version

v0.0.92

### Python version

3.11.5

### Operating System

Ubuntu 22

### Dependencies

absl-py==2.1.0
aiofiles==23.2.1
annotated-types==0.6.0
anyio==4.3.0
archspec @ file:///croot/archspec_1697725767277/work
astunparse==1.6.3
beautifulsoup4==4.12.3
blinker==1.8.2
boltons @ file:///work/ci_py311/boltons_1677685195580/work
Brotli @ file:///work/ci_py311/brotli-split_1676830125088/work
certifi @ file:///croot/certifi_1700501669400/work/certifi
cffi @ file:///croot/cffi_1700254295673/work
charset-normalizer @ file:///tmp/build/80754af9/charset-normalizer_1630003229654/work
click==8.1.7
conda @ file:///croot/conda_1701719518285/work
conda-content-trust @ file:///croot/conda-content-trust_1693490622020/work
conda-libmamba-solver @ file:///croot/conda-libmamba-solver_1702997573971/work/src
conda-package-handling @ file:///croot/conda-package-handling_1690999929514/work
conda_package_streaming @ file:///croot/conda-package-streaming_1690987966409/work
contourpy==1.2.1
cryptography @ file:///croot/cryptography_1702070282333/work
cycler==0.12.1
deepface==0.0.92
dill==0.3.8
distro @ file:///croot/distro_1701455004953/work
dlib==19.24.2
dnspython==2.6.1
email_validator==2.1.1
face-recognition==1.3.0
face-recognition-models==0.3.0
fastapi==0.110.0
filelock==3.15.4
fire==0.6.0
Flask==3.0.3
flatbuffers==24.3.25
fonttools==4.53.1
fsspec==2024.6.1
gast==0.6.0
gdown==5.2.0
google-pasta==0.2.0
grpcio==1.64.1
gunicorn==22.0.0
h11==0.14.0
h5py==3.11.0
httpcore==1.0.5
httptools==0.6.1
httpx==0.27.0
idna @ file:///work/ci_py311/idna_1676822698822/work
itsdangerous==2.1.2
Jinja2==3.1.3
jsonpatch @ file:///tmp/build/80754af9/jsonpatch_1615747632069/work
jsonpointer==2.1
keras==3.4.1
kiwisolver==1.4.5
libclang==18.1.1
libmambapy @ file:///croot/mamba-split_1698782620632/work/libmambapy
Markdown==3.6
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.9.1
mdurl==0.1.2
menuinst @ file:///croot/menuinst_1702390294373/work
ml-dtypes==0.3.2
mpmath==1.3.0
mtcnn==0.1.1
namex==0.0.8
networkx==3.3
numpy==1.26.4
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.20.5
nvidia-nvjitlink-cu12==12.5.82
nvidia-nvtx-cu12==12.1.105
opencv-python==4.10.0.84
opt-einsum==3.3.0
optree==0.12.1
orjson==3.10.0
packaging @ file:///croot/packaging_1693575174725/work
pandas==2.2.2
pillow==10.2.0
platformdirs @ file:///croot/platformdirs_1692205439124/work
pluggy @ file:///work/ci_py311/pluggy_1676822818071/work
protobuf==4.25.3
psutil==6.0.0
py-cpuinfo==9.0.0
pycosat @ file:///croot/pycosat_1696536503704/work
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
pydantic==2.6.4
pydantic-extra-types==2.6.0
pydantic-settings==2.2.1
pydantic_core==2.16.3
Pygments==2.18.0
pyOpenSSL @ file:///croot/pyopenssl_1690223430423/work
pyparsing==3.1.2
PySocks @ file:///work/ci_py311/pysocks_1676822712504/work
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
python-multipart==0.0.9
pytz==2024.1
PyYAML==6.0.1
redis==5.0.7
requests @ file:///croot/requests_1690400202158/work
retina-face==0.0.17
rich==13.7.1
ruamel.yaml @ file:///work/ci_py311/ruamel.yaml_1676838772170/work
scipy==1.14.0
seaborn==0.13.2
six==1.16.0
sniffio==1.3.1
soupsieve==2.5
starlette==0.36.3
sympy==1.12.1
tensorboard==2.16.2
tensorboard-data-server==0.7.2
tensorflow==2.16.2
tensorflow-io-gcs-filesystem==0.37.1
termcolor==2.4.0
tf_keras==2.16.0
torch==2.3.1
torchvision==0.18.1
tqdm @ file:///croot/tqdm_1679561862951/work
triton==2.3.1
truststore @ file:///croot/truststore_1695244293384/work
typing_extensions==4.10.0
tzdata==2024.1
ujson==5.9.0
ultralytics==8.2.51
ultralytics-thop==2.0.0
urllib3 @ file:///croot/urllib3_1698257533958/work
uvicorn==0.29.0
uvloop==0.19.0
watchfiles==0.21.0
websockets==12.0
Werkzeug==3.0.3
wrapt==1.16.0
zstandard @ file:///work/ci_py311_2/zstandard_1679339489613/work

### Reproducible example

```Python
models = [
  "VGG-Face", #0
  "ArcFace",  #1
  "Dlib",  #2
]

#embeddings
embedding_objs = DeepFace.represent(
  img_path = "./faces/4_crop.jpg",
  model_name = models[2], #...also tried 0,1 with no luck
)
```

### Relevant Log Output

Traceback (most recent call last):
  File "/var/www/luuv/yolo/recog_deepface.py", line 17, in <module>
    embedding_objs = DeepFace.represent(
                     ^^^^^^^^^^^^^^^^^^^
  File "/home/alexrsk/miniconda3/lib/python3.11/site-packages/deepface/DeepFace.py", line 409, in represent
    return representation.represent(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexrsk/miniconda3/lib/python3.11/site-packages/deepface/modules/representation.py", line 71, in represent
    img_objs = detection.extract_faces(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexrsk/miniconda3/lib/python3.11/site-packages/deepface/modules/detection.py", line 96, in extract_faces
    raise ValueError(
ValueError: Face could not be detected in ./faces/4_crop.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.

### Expected Result

Face found

### What happened instead?

Face not found

### Additional Info

I previously used [face_recognition](https://github.com/ageitgey/face_recognition) package to detect and recognize faces.
It is able to recognize mostly faces with straight angle. I decided to improve angle of recognition, and downloaded DeepFace with different faces models. 
I applied a file with face, which was not detected not by one provided face models of DeepFace!

On the other hand, the obsolete ageitgey/face_recognition based on the DLib (provided in DeepFace too), successfully detects it! 

![4_crop](https://github.com/serengil/deepface/assets/16610797/466f72c2-f963-4b90-8d62-8b66328e473e)

**Comment by serengil** [comment] 2024-07-12 10:44
you may try to use a better detector such as retinaface. did you try it?

secondly, this is not the ageitgey/face_recognition. if it can detect side images, then it is using different configuration.

this is how dlib detector is being used in deepface: https://github.com/serengil/deepface/blob/master/deepface/detectors/Dlib.py#L74C33-L74C46

but this is not a bug, that is why i am closing this.

**Closed by serengil** 2024-07-12 10:44 UTC
Labels: bug
