### ISSUE TITLE
BUG: RetinaFace does not work from Deepface

### ISSUE THREAD

**Issue by sadimoodi** [serengil/deepface#370] opened 2021-11-16 09:54 UTC
Hello,
When using retina face from within deepface by directly using DeepFace.detectFace raises an error "face not found" like this:
```
df_faces = DeepFace.detectFace(img_path = "./database/Moodi_old.jpg",detector_backend='retinaface',enforce_detection=True,align=True)
cv2.imshow('test',df_faces)
cv2.waitKey(0)
````
ValueError: Face could not be detected. Please confirm that the picture is a face photo or consider to set enforce_detection param to 
False.

when calling RetinaFace.extract_faces I get the face corretly: 

```
faces = RetinaFace.extract_faces(img_path = "./database/Moodi_old.jpg", align = True)
for face in faces:
  cv2.imshow('test',face)
  cv2.waitKey(0)
```

**Note that i am NOT going through the stream anymore, although i already applied the bug fixes you mentioned in other issues.**

**Comment by serengil** [comment] 2021-11-19 06:16
would you please share database/Moodi_old.jpg here. I can fix it in the weekend.

**Comment by sadimoodi** [comment] 2021-11-21 06:38
I already fixed it, change the code inside retinafacewrapper.py to :
```
            if align:
                landmarks = identity["landmarks"]
                left_eye = landmarks["left_eye"]
                right_eye = landmarks["right_eye"]
                #nose = landmarks["nose"]
                #mouth_right = landmarks["mouth_right"]
                #mouth_left = landmarks["mouth_left"]

                detected_face = postprocess.alignment_procedure(detected_face, right_eye, left_eye)
```
I removed nose from the alignment process because this is way its done in the original code of retinaface

**Comment by tensorslow** [comment] 2021-11-28 04:38
Hello everyone!

I have also been experiencing this error with retinaface:
“ValueError: Face could not be detected. Please confirm that the picture is a face photo or consider to set enforce_detection param to False.”

Unfortunately, removing “nose” from the above-mentioned segment of code didn’t help me as described by the original poster, but I have found a simple, reproducible way of inducing or "resolving" this problem, and it can be tested with any picture. Just pre-crop the face in the image to be roughly the size you’d expected it to be based on bounding boxes, and this error occurs when using retinaface as your detector in deepface. If you crop further out so that the face isn’t occupying so much of the image (or just paste the pre-cropped image into any other larger image and use that one) retinaface will detect the face properly. This seems to be true regardless of image size or any other factor I tested. An example is included below. The image in the top link works perfectly with retinaface as the detector, while the bottom one (same image but cropped) does not (at least on my system).

I hope this information helps.

(https://user-images.githubusercontent.com/93057356/143729429-d5d97cc7-7412-4e59-8347-464d174a62e7.png)

(https://user-images.githubusercontent.com/93057356/143729432-32a6b602-868b-4ace-82ad-cd3827811287.png)

.

**Comment by serengil** [comment] 2021-12-23 07:10
retinaface code repo is updated and I'm going to publish it in pip in the next couple of days. This is going to be resolved with this version.

**Closed by serengil** 2021-12-23 07:10 UTC
Labels: bug

**Comment by erickcrus** [comment] 2022-11-22 19:16
im having same issue. My code:
```
from deepface import DeepFace
from retinaface import RetinaFace

img_path = './tmp/'+filename

faces = RetinaFace.extract_faces(img_path)
if len(faces) != 1:           # count number of faces in image
       return { 'success':False, 'message':'We accept images with one face only.' }

df = DeepFace.find( img_path=img_path,
     db_path='./images/datasets',
     model_name='Facenet512',
     detector_backend='retinaface',
     distance_metric='euclidean_l2' )

print(df)
```

This code return this error: "Face could not be detected. Please confirm that the picture is a face photo or consider to set enforce_detection param to False."

All images in folder `./images/datasets` are normalized, and faces was pre-processed. The folder contains 40000+ faces from my DB.

**Comment by DKCopy** [comment] 2023-01-09 04:36
It can fixed, change the code inside `deepface\detectors\RetinaFaceWrapper.py` to:

#resp.append((detected_face, img_region, confidence))
resp.append((detected_face, img_region))
